// <auto-generated />
using System;
using DBSeniorLearnApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBSeniorLearnApp.UI.Data.Migrations.Service
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20251102091840_AddedCourseEnrolments")]
    partial class AddedCourseEnrolments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Prerequisites")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.CourseEnrolments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId");

                    b.ToTable("CourseEnrolments");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdatedPaidStatus")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("PaidStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasAlternateKey("MemberNumber");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.ProfessionalMember", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHonoraryMember")
                        .HasColumnType("bit");

                    b.HasKey("MemberId");

                    b.ToTable("ProfessionalMembers");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.Course", b =>
                {
                    b.HasOne("DBSeniorLearnApp.DataAccess.Models.ProfessionalMember", "ProfessionalMember")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalMember");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.CourseEnrolments", b =>
                {
                    b.HasOne("DBSeniorLearnApp.DataAccess.Models.Course", "Course")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBSeniorLearnApp.DataAccess.Models.Member", "Member")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.ProfessionalMember", b =>
                {
                    b.HasOne("DBSeniorLearnApp.DataAccess.Models.Member", "Member")
                        .WithOne("ProfessionalMember")
                        .HasForeignKey("DBSeniorLearnApp.DataAccess.Models.ProfessionalMember", "MemberId")
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.Course", b =>
                {
                    b.Navigation("CourseEnrolments");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.Member", b =>
                {
                    b.Navigation("CourseEnrolments");

                    b.Navigation("ProfessionalMember");
                });

            modelBuilder.Entity("DBSeniorLearnApp.DataAccess.Models.ProfessionalMember", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
